# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

languages: ["es", "en"]
languages_long_names:
  es: Español
  en: English
default_lang: "en"
exclude_from_localization: ["assets"]
excerpt_separator: <!--more-->

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
title: Josué Álvarez Moreno
google_analytics: UA-104442288-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title:
        es: Blog de Josué Álvarez Moreno
        en: Josué Álvarez Moreno's blog

description:  Blog de Josué Álvarez Moreno, donde almaceno notas y conocimiento para mí y para todos.
author:
  name: Josué Álvarez Moreno
  email: blog@josuealvarezmoreno.com
  github: j-alvarez-moreno
  linkedin: josué-álvarez-moreno-b88896144
  bio:
    es: Administrador de Sistemas.
    en: System Administrator.
  email_md5: da3470a132e93bfe23072dccad7e2956

categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate

# I will need to split this into it's own config file, but it will suffice for testing purposes.

translations:
  en:
    read_more: "View full post."
    estimated_read_time: "Estimated reading time"
    read: "Estimated reading time: "
    minute: "minute"
    minutes: "minutes"
  es:
    read_more: "Ver post completo."
    estimated_read_time: "Tiempo de lectura estimado"
    minute: "minuto"
    minutes: "minutos"
    read: "Tiempo estimado de lectura: "
